#!/bin/bash
#Author: Matteo Veroni

export SMART_ACTIONS_PROJECT_DIR="/opt/FasterWhisper"
export SMART_ACTIONS_COMMAND_BUILDER_OUTPUT_FILE=/tmp/smart_actions_command_builder_output_file

# Funzione dinamica per invocare gli script
invoke_action() {
  action_name="${FUNCNAME[1]}"  # Ottieni il nome della funzione chiamante
  action_script="${SMART_ACTIONS_PROJECT_DIR}/actions/${action_name}/action.sh"

  # Verifica se lo script esiste
  if [[ -f "$action_script" ]]; then
    "$action_script" "$@"  # Passa gli argomenti al comando
  else
    echo "Error: Script for action '$action_name' does not exist!"
    exit 1
  fi
}

# Ciclo che esplora la cartella actions e crea le funzioni dinamicamente
for action_dir in "$SMART_ACTIONS_PROJECT_DIR/actions"/*/; do
  # Estrai il nome della cartella (rimuovi la parte finale '/')
  action_name=$(basename "$action_dir")

  # Crea una funzione per ogni cartella in actions
  eval "
    $action_name() {
      invoke_action \"\$@\"
    }
  "
done

# TODO: this is valid only for commands which record audio, not for the others (eg. audio_to_text)
end() {
  echo "Stopping the process..."
  pkill -f "arecord" # Uccide il processo di registrazione (se in esecuzione)
}

help() {
  echo "Usage: $0 {start|stop|help}"
  echo
  echo "audio_to_text - Convert an audio file to a text. (it needs a -f parameter specifying the path of the audio file to transcript"
  echo "dictate_text - Record an audio and convert it to text"
  echo "dictate_command - Record an audio and convert it into a text line terminated by the enter key (command)."
  echo "ai_reply_text - Record an audio question and provide a text response generated by an AI."
  echo "ai_reply_text_for_selection - Record an audio question about a selected text and provide a text response generated by an AI."
  echo "ai_reply_text_for_copy - Record an audio question about a text present in the clipboard (copied text) and provide a text response generated by an AI."
  echo "ai_reply_terminal - Record an audio question and provide a text response in the terminal."
  echo "end - Stop the recording and ongoing processes."
  echo "help - Show this help message."
  echo
  echo "Examples:"
  echo "./smart-actions.sh dictate_text - Start audio recording and convert it to text (stop the recording with CTRL+C or end)."
  echo "./smart-actions.sh end - Stop the recording if it's in progress."
  echo "./smart-actions.sh audio_to_text -f /home/file.wav"
}

mkdir -p /tmp
touch "$SMART_ACTIONS_COMMAND_BUILDER_OUTPUT_FILE"

case "$1" in
audio_to_text)
  shift
  audio_to_text "$@"
  ;;
dictate_text)
  shift
  dictate_text "$@"
  ;;
dictate_command)
  shift
  dictate_command "$@"
  ;;
ai_reply_text)
  shift
  ai_reply_text "$@"
  ;;
end)
  end
  ;;
help)
  help
  ;;
*)
  help
  exit 1
  ;;
esac

unset $SMART_ACTIONS_COMMAND_BUILDER_OUTPUT_FILE
